name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
    
  flutter_dotenv: ^5.0.2


  # Icônes Cupertino pour iOS
  cupertino_icons: ^1.0.8

  # Requêtes HTTP
  http: ^1.3.0

  # Gestion d'état avec Provider
  provider: ^6.1.2

  # Ouvrir des URLs dans le navigateur ou d'autres applications
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


